/**
 * 初始示例数据
 * 用于恢复出厂设置时保留示例数据
 */

export const initialCategories = [
  {
    id: 'cat-tools',
    name: '常用工具',
    icon: 'Wrench',
    color: '#3b82f6',
    orderIndex: 0,
    description: '日常使用的在线工具',
  },
  {
    id: 'cat-dev',
    name: '开发资源',
    icon: 'Code',
    color: '#10b981',
    orderIndex: 1,
    description: '开发相关的工具和文档',
  },
  {
    id: 'cat-design',
    name: '设计灵感',
    icon: 'Palette',
    color: '#f59e0b',
    orderIndex: 2,
    description: '设计资源和灵感来源',
  },
  {
    id: 'cat-learn',
    name: '学习资料',
    icon: 'BookOpen',
    color: '#8b5cf6',
    orderIndex: 3,
    description: '学习资源和教程',
  },
  {
    id: 'cat-ent',
    name: '休闲娱乐',
    icon: 'Gamepad2',
    color: '#ec4899',
    orderIndex: 4,
    description: '娱乐和休闲网站',
  },
]

export const initialBookmarks = [
  // 常用工具（国内可访问）
  {
    id: 'bm-baidu',
    url: 'https://www.baidu.com',
    title: '百度',
    description: '百度一下，你就知道',
    category: 'cat-tools',
    tags: '搜索,工具',
    orderIndex: 0,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-bing',
    url: 'https://www.bing.com',
    title: '必应',
    description: '微软必应搜索引擎',
    category: 'cat-tools',
    tags: '搜索,工具',
    orderIndex: 1,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-yiyan',
    url: 'https://yiyan.baidu.com',
    title: '文心一言',
    description: '百度AI对话助手',
    category: 'cat-tools',
    tags: 'AI,工具,对话',
    orderIndex: 2,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-gitee',
    url: 'https://gitee.com',
    title: 'Gitee',
    description: '国内领先的代码托管平台',
    category: 'cat-dev',
    tags: '代码,开源,协作',
    orderIndex: 0,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-juejin',
    url: 'https://juejin.cn',
    title: '掘金',
    description: '程序员技术社区',
    category: 'cat-dev',
    tags: '技术,编程,社区',
    orderIndex: 1,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-zhihu',
    url: 'https://www.zhihu.com',
    title: '知乎',
    description: '中文互联网问答社区',
    category: 'cat-learn',
    tags: '问答,知识,社区',
    orderIndex: 0,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-bilibili',
    url: 'https://www.bilibili.com',
    title: '哔哩哔哩',
    description: '国内知名的视频弹幕网站',
    category: 'cat-ent',
    tags: '视频,娱乐,学习',
    orderIndex: 0,
    isPinned: true,
    visibility: 'public',
  },
  {
    id: 'bm-doubao',
    url: 'https://www.doubao.com',
    title: '豆包',
    description: '字节跳动AI助手',
    category: 'cat-tools',
    tags: 'AI,工具,对话',
    orderIndex: 3,
    isPinned: false,
    visibility: 'public',
  },
]

export const initialQuotes = [
  {
    id: 'quote-1',
    content: '知识就是力量',
    source: '培根',
    orderIndex: 0,
  },
  {
    id: 'quote-2',
    content: '学而时习之，不亦说乎',
    source: '孔子',
    orderIndex: 1,
  },
  {
    id: 'quote-3',
    content: '千里之行，始于足下',
    source: '老子',
    orderIndex: 2,
  },
]

export const initialSettings = {
  siteTitle: 'Nexus',
  siteDescription: '一个简洁优雅的导航主页',
  enableAnimation: true,
  enableParticles: true,
  privateMode: false,
  showSearch: true,
  searchEngine: 'google',
  showDateTime: true,
  showWeather: true,
  showQuote: true,
  showVisits: true,
}
